// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4532VKXIevMFdSDHvjCiHCLPpdVd0jII',
    appId: '1:169318012210:web:3be682a9891f16e176732b',
    messagingSenderId: '169318012210',
    projectId: 'flutter-first-3fe64',
    authDomain: 'flutter-first-3fe64.firebaseapp.com',
    storageBucket: 'flutter-first-3fe64.appspot.com',
    measurementId: 'G-ETVS3ZHNLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMKR49BeILZHedYii3SuWd4YWkxrcYFX4',
    appId: '1:169318012210:android:f0b6f2df72cd8a0376732b',
    messagingSenderId: '169318012210',
    projectId: 'flutter-first-3fe64',
    storageBucket: 'flutter-first-3fe64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXsdVZKQ-644sN5p7voOm63yjK9eB-SOI',
    appId: '1:169318012210:ios:2b4b2c998a351ee276732b',
    messagingSenderId: '169318012210',
    projectId: 'flutter-first-3fe64',
    storageBucket: 'flutter-first-3fe64.appspot.com',
    iosBundleId: 'com.example.flutterFirst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXsdVZKQ-644sN5p7voOm63yjK9eB-SOI',
    appId: '1:169318012210:ios:09a3ab885e7218e576732b',
    messagingSenderId: '169318012210',
    projectId: 'flutter-first-3fe64',
    storageBucket: 'flutter-first-3fe64.appspot.com',
    iosBundleId: 'com.example.flutterFirst.RunnerTests',
  );
}
